# model-service/docker-compose.yml
services:
  model-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs
      - ./models:/app/models
      - ./.env:/app/.env
    # Load **all** variables exactly as written in .env
    # This avoids host / global env values overriding the file
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - model-manager-network
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  model-manager-network:
    driver: bridge
  microservices-network:
    external: true