deployment: !Deployment
  destination: aws
  endpoint_name: deepset--roberta-base-squad2-08d0d8ed-202504211220
  instance_count: 1
  instance_type: ml.m5.xlarge
  num_gpus: null
  quantization: null
models:
- !Model
  id: deepset/roberta-base-squad2
  location: null
  predict: null
  source: huggingface
  task: question-answering
  version: null
