deployment: !Deployment
  destination: aws
  endpoint_name: google-bert--bert-base-uncased-202504151451-202504151451
  instance_count: 1
  instance_type: ml.m5.xlarge
  num_gpus: null
  quantization: null
models:
- !Model
  id: google-bert/bert-base-uncased
  location: null
  predict: null
  source: huggingface
  task: fill-mask
  version: null
