deployment: !Deployment
  destination: aws
  endpoint_name: gpt2-bcfc6d40-202506021504
  instance_count: 1
  instance_type: ml.m5.xlarge
  num_gpus: null
  quantization: null
models:
- !Model
  id: gpt2
  location: null
  predict: null
  source: huggingface
  task: text-generation
  version: null
